name: PreProcessing + PostProcessing CI

on:
  schedule:
    # 每天 UTC 0:10 自动执行
    - cron: "10 0 * * *"
  workflow_dispatch:  # 支持手动触发
  pull_request:
    branches:
      - main
  push:
    branches:
      - main  # merge 到 main

jobs:
  run-preprocessing:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Run PreProcessing.dll
        working-directory: ./translation_utils
        run: dotnet PreProcessing.dll

  run-postprocessing:
    needs: run-preprocessing
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run PostProcessing.exe
        working-directory: ./translation_utils
        run: dotnet PostProcessing.dll
